FastFoodStore_Client/Areas/Admin/Controllers/ComboController.cs
using FastFoodStore_Client.Models;
using FastFoodStore_Client.Attribute;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FastFoodStore_Client.Areas.Admin.Controllers
{
    [Area("Admin")]
    [CheckUserLogin]
    public class ComboController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IWebHostEnvironment _environment;

        public ComboController(IHttpClientFactory httpClientFactory, IWebHostEnvironment environment)
        {
            _httpClient = httpClientFactory.CreateClient("FastFoodStore_API");
            _environment = environment;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var response = await _httpClient.GetStringAsync("Admin/Combo/Index");
                var combo = JsonConvert.DeserializeObject<List<Combo>>(response);
                return View(combo);
            }
            catch (Exception)
            {
                return View(new List<Combo>());
            }
        }
        public async Task<IActionResult> Details(int id)
        {
            var response = await _httpClient.GetStringAsync($"Admin/Combo/Details/{id}");
            var combo = JsonConvert.DeserializeObject<Combo>(response);
            return View(combo);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Combo combo, IFormFile? imageFile)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var errors = ModelState.Values.SelectMany(v => v.Errors);
                    foreach (var error in errors)
                    {
                        Console.WriteLine(error.ErrorMessage);
                    }
                    return View(combo);
                }
                // Tạo MultipartFormDataContent để chứa dữ liệu
                using (var content = new MultipartFormDataContent())
                {
                    // Thêm các trường của FoodItem vào form
                    content.Add(new StringContent(combo.ComboName ?? string.Empty), "ComboName");
                    content.Add(new StringContent(combo.Description ?? string.Empty), "Description");
                    content.Add(new StringContent(combo.Price.ToString()), "Price");
                    var imageFileName = Path.GetFileName(imageFile!.FileName); 
                    var response = await _httpClient.PostAsync($"Admin/Combo/Create?imageFileName={imageFileName}", content);

                    if (response.IsSuccessStatusCode)
                    {
                        await SaveImageAsync(imageFile); 
                        return RedirectToAction(nameof(Index)); 
                    }
                    else
                    {
                        var errorContent = await response.Content.ReadAsStringAsync();
                        Console.WriteLine("Lỗi từ API: " + errorContent);
                    }
                }

                return View(combo);
            }
            catch (HttpRequestException ex)
            {
                ViewBag.ErrorMessage = "Lỗi kết nối API: " + ex.Message;
            }
            catch (JsonException)
            {
                ViewBag.ErrorMessage = "Lỗi xử lý dữ liệu từ API.";
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Đã xảy ra lỗi khi tạo combo.", error = ex.Message });
            }
            return View(combo);
        }

        private async Task<string> SaveImageAsync(IFormFile imageFile)
        {
            // Đường dẫn đến thư mục food_menu
            string uploadsFolder = Path.Combine(_environment.WebRootPath, "img/food_item");

            // Kiểm tra nếu thư mục chưa tồn tại thì tạo mới
            if (!Directory.Exists(uploadsFolder))
            {
                Directory.CreateDirectory(uploadsFolder);
            }
            string filePath = Path.Combine(uploadsFolder, imageFile.FileName);

            // Lưu ảnh vào thư mục
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                await imageFile.CopyToAsync(fileStream);
            }
            // Trả về đường dẫn ảnh (relatively to the web root)
            return imageFile.FileName;
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var response = await _httpClient.GetStringAsync($"Admin/Combo/Details/{id}");
            var combo = JsonConvert.DeserializeObject<Combo>(response);
            return View(combo);
        }

        public async Task<IActionResult> Edit(int id, Combo combo, IFormFile? imageFile)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    var errors = ModelState.Values.SelectMany(v => v.Errors);
                    foreach (var error in errors)
                    {
                        Console.WriteLine(error.ErrorMessage);
                    }
                    return View(combo);
                }

                // Lấy tên file hình ảnh (nếu có)
                string imageFileName = imageFile != null ? imageFile.FileName : string.Empty;

                if (string.IsNullOrEmpty(imageFileName))
                {
                    ModelState.AddModelError("ImageFile", "Hình ảnh không được để trống.");
                    return View(combo);
                }

                // Tạo MultipartFormDataContent để chứa dữ liệu
                using (var content = new MultipartFormDataContent())
                {
                    // Thêm các trường của FoodItem vào form
                    content.Add(new StringContent(combo.ComboName ?? string.Empty), "ComboName");
                    content.Add(new StringContent(combo.Description ?? string.Empty), "Description");
                    content.Add(new StringContent(combo.Price.ToString()), "Price");
                    content.Add(new StringContent(imageFileName), "imageFileName");
                    var response = await _httpClient.PutAsync($"Admin/Combo/Edit/{id}?imageFileName={imageFileName}", content);

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        // Đọc nội dung lỗi nếu có
                        var errorContent = await response.Content.ReadAsStringAsync();
                        Console.WriteLine(errorContent);
                    }
                }

                return View(combo);
            }
            catch (HttpRequestException ex)
            {
                ViewBag.ErrorMessage = "Lỗi kết nối API: " + ex.Message;
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Đã xảy ra lỗi khi chỉnh sửa sản phẩm.", error = ex.Message });
            }

            return View(combo);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var response = await _httpClient.GetStringAsync($"Admin/Combo/Details/{id}");
            var combo = JsonConvert.DeserializeObject<Combo>(response);
            return View(combo);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var response = await _httpClient.DeleteAsync($"Admin/Combo/DeleteConfirmed/{id}");

                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    var errorContent = await response.Content.ReadAsStringAsync();
                    Console.WriteLine(errorContent);
                }
            }
            catch (HttpRequestException ex)
            {
                ViewBag.ErrorMessage = "Lỗi kết nối API: " + ex.Message;
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Đã xảy ra lỗi khi xóa sản phẩm.", error = ex.Message });
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

FastFoodStore_Client/Areas/Admin/Controllers/UserController.cs
using FastFoodStore_Client.Attribute;
using FastFoodStore_Client.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FastFoodStore_Client.Areas.Admin.Controllers
{
    [Area("Admin")]
    [CheckUserLogin]
    public class UserController : Controller
    {
        private readonly HttpClient _httpClient;

        public UserController(IHttpClientFactory httpClientFactory)
        {
            _httpClient = httpClientFactory.CreateClient("FastFoodStore_API");
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var response = await _httpClient.GetStringAsync("Admin/User/Index");
                var listuser = JsonConvert.DeserializeObject<List<User>>(response);
                return View(listuser);
            }
            catch (Exception)
            {
                return View(new List<User>());
            }
        }

        public async Task<IActionResult> Detail(string id)
        {
            var response = await _httpClient.GetStringAsync($"Admin/User/Detail/{id}");
            var detailuser = JsonConvert.DeserializeObject<User>(response);
            return View(detailuser);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(User enduser)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("Index", enduser);
                }
                if (enduser == null)
                {
                    return BadRequest();
                }
                //var content = new StringContent(JsonConvert.SerializeObject(enduser), Encoding.UTF8, "application/json");
                var response = await _httpClient.PostAsJsonAsync($"Admin/User/Create", enduser);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View("Create", enduser);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        public async Task<IActionResult> Update(string id)
        {
            var response = await _httpClient.GetStringAsync($"Admin/User/Detail/{id}");
            var user = JsonConvert.DeserializeObject<User>(response);
            return View(user);
        }
        [HttpPost]
        public async Task<IActionResult> Update(User user)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View("Index", user);
                }
                if (user == null)
                {
                    return BadRequest();
                }
                var response = await _httpClient.PutAsJsonAsync($"Admin/User/Update?id={user.Id}", user);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View("Update", user);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }
        public async Task<IActionResult> Delete(string id)
        {
            var response = await _httpClient.GetStringAsync($"Admin/User/Detail/{id}");
            var user = JsonConvert.DeserializeObject<User>(response);
            return View(user);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            try
            {
                var response = await _httpClient.DeleteAsync($"Admin/User/DeleteConfirmed/{id}");
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction(nameof(Index));
                }
                return View("Delete", id);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
        }

        //public async Task<IActionResult> Delete(string id)
        //{
        //    var user = await _crudUser.GetUserByIdAsync(id);
        //    if (user == null) return NotFound();
        //    return View(user);
        //}

        //[HttpPost, ActionName("Delete")]
        //public async Task<IActionResult> DeleteConfirmed(string id)
        //{
        //    await _crudUser.DeleteUserAsync(id);
        //    return RedirectToAction("Index");
        //}
    }
}

FastFoodStore_Client/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Trang Admin</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700">
    <!-- https://fonts.google.com/specimen/Roboto -->
    <link rel="stylesheet" href="~/cssAdmin/fontawesome.min.css">
    <!-- https://fontawesome.com/ -->
    <link rel="stylesheet" href="~/cssAdmin/bootstrap.min.css">
    <!-- https://getbootstrap.com/ -->
    <link rel="stylesheet" href="~/cssAdmin/templatemo-style.css">
    <!--
    Product Admin CSS Template
    https://templatemo.com/tm-524-product-admin
    -->
    @RenderSection("Css", required: false)
</head>

<body id="reportsPage">
    <div class="" id="home">
        <nav class="navbar navbar-expand-xl">
            <div class="container h-100">
                <a class="navbar-brand" href="Admin.html">
                    <h1 class="tm-site-title mb-0"><a asp-area="Admin" asp-controller="Home" asp-action="Index">Fast Food Store Management</a></h1>
                </a>
                <button class="navbar-toggler ml-auto mr-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars tm-nav-icon"></i>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mx-auto h-100">
                        <li class="nav-item">
                            <a class="nav-link active" href="#">
                                <i class="fas fa-tachometer-alt"></i>
                                Statistical
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>   
                        <li class="nav-item dropdown">

                            <a class="nav-link dropdown-toggle" asp-area="Admin" asp-controller="Home" asp-action="Index" id="navbarDropdown" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                <i class="far fa-file-alt"></i>
                                <span>
                                    Management <i class="fas fa-angle-down"></i>
                                </span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">User Management</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="FoodItem" asp-action="Index">Food Management</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Combo" asp-action="Index">Combo Management</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Order" asp-action="Index">Delivery Management</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-cog"></i>
                                <span>
                                    Setting <i class="fas fa-angle-down"></i>
                                </span>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Home" asp-action="Detail">Your Account</a>
                                <a class="dropdown-item" href="#">Setting</a>
                            </div>
                        </li>
                    </ul>
                    <ul class="navbar-nav">
                        @{
                            var adId = Context.Session.GetString("AdminId");
                            var adName = Context.Session.GetString("AdminName");
                        }
                        <li class="nav-item">
                            <a class="nav-link d-block" asp-area="Admin" asp-controller="Home" asp-action="Login">
                                Hello: @adName <b>Logout</b>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

        </nav>
@RenderBody()
        <footer class="tm-footer row tm-mt-small">
            <div class="col-12 font-weight-light">
                <p class="text-center text-white mb-0 px-4 small">
                    Copyright &copy; <b>2024</b> All rights reserved.

                    Design: <a rel="nofollow noopener" href="http://anhhoangtranluu.xyz/" class="tm-footer-link">TranLuu</a>
                </p>
            </div>
        </footer>
    </div>

    <script src="~/jsAdmin/jquery-3.3.1.min.js"></script>
    <!-- https://jquery.com/download/ -->
    <script src="~/jsAdmin/moment.min.js"></script>
    <!-- https://momentjs.com/ -->
    <script src="~/jsAdmin/Chart.min.js"></script>
    <!-- http://www.chartjs.org/docs/latest/ -->
    <script src="~/jsAdmin/bootstrap.min.js"></script>
    <!-- https://getbootstrap.com/ -->
    <script src="~/jsAdmin/tooplate-scripts.js"></script>
    <script>
        Chart.defaults.global.defaultFontColor = 'white';
        let ctxLine,
            ctxBar,
            ctxPie,
            optionsLine,
            optionsBar,
            optionsPie,
            configLine,
            configBar,
            configPie,
            lineChart;
        barChart, pieChart;
        // DOM is ready
        $(function () {
            drawLineChart(); // Line Chart
            drawBarChart(); // Bar Chart
            drawPieChart(); // Pie Chart

            $(window).resize(function () {
                updateLineChart();
                updateBarChart();
            });
        })
    </script>
    @RenderSection("scripts", required: false)
</body>

</html>